config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :omniauth_callbacks,
    registrations: :registrations
  }
  root 'welcome#index'

  get 'explore' => 'welcome#explore', as: :explore
  get 'explore/:category' => 'welcome#explore', as: :explore_category
  get 'challenge' => 'welcome#challenge'
  get 'about' => 'welcome#about'

  scope :upload, controller: :uploads, as: :upload do
    get :new
    post :create
    get 'share/:id', action: :share, as: :share
  end

  resources :songs, only: [:new, :create, :show] do
    member do
      get :share
      post :vote
      get :play
    end
  end

  resources :users, only: [:show]
end

app/models/song.rb
class Song < ActiveRecord::Base
  before_validation :prepare

  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy
  has_many :plays, dependent: :destroy

  mount_uploader :image, SongImageUploader

  validates :user, :category, :url, :provider, :provider_id, presence: true
  validates_uniqueness_of :provider_id, scope: :provider, message: 'This track already has been added'


  scope :latest, -> { order(created_at: :desc) }
  scope :top, ->(start_date=nil, end_date=nil) {
    if start_date.present? && end_date.present?
      select('COALESCE(v_count, 0) + COALESCE(p_count, 0) AS songs_score, songs.*')
      .joins("LEFT JOIN (
        SELECT COUNT(votes.id) AS v_count, votes.song_id as votes_song_id
        FROM votes
        WHERE (votes.created_at BETWEEN '#{start_date} 00:00:00' AND '#{end_date} 23:59:59')
        GROUP BY votes.song_id
      ) v ON v.votes_song_id = songs.id")
      .joins("LEFT JOIN (
        SELECT COUNT(plays.id) AS p_count, plays.song_id as plays_song_id
        FROM plays
        WHERE (plays.created_at BETWEEN '#{start_date} 00:00:00' AND '#{end_date} 23:59:59')
        GROUP BY plays.song_id
      ) p ON p.plays_song_id = songs.id")
      .order('songs_score DESC, songs.votes_count DESC, songs.plays_count DESC')
    else
      select('songs.votes_count + songs.plays_count AS songs_score, songs.*')
      .order('songs_score DESC, songs.votes_count DESC, songs.plays_count DESC')
    end
    }
  scope :for_challenge, -> { where(for_challenge: true) }

  def original_song
    Song.where(provider: provider, provider_id: provider_id).order(created_at: :desc).first
  end

  private
  def prepare
    return if persisted? or url.blank?

    if self.url.match 'soundcloud.com'
      client = Soundcloud.new(client_id: ENV['soundcloud_id'])

      begin
        track = client.get('/resolve', url: self.url)
      rescue Soundcloud::ResponseError => e
        self.errors.add :url, "video was not found, check your url"
        return
      end

      self.provider = 'soundcloud'
      self.provider_id = track.id
      self.title = track.title
      self.description = track.description
      self.remote_image_url = track.artwork_url.gsub('-large', '-t500x500')

    elsif self.url.match 'youtu.be|youtube.com'
      provider_id = CGI.parse(URI.parse(self.url).query)['v'].first
      client = Yourub::Client.new

      track = client.get provider_id
      unless track
        self.errors.add :url, "video was not found, check your url"
        return
      end

      self.provider = 'youtube'
      self.provider_id = track['id']
      self.title = track['snippet']['title']
      self.description = track['snippet']['description']
      self.remote_image_url = track["snippet"]["thumbnails"].values.last["url"]

    else
      self.errors.add :url, "provider not recognized"
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: [:share, :show]
  before_filter :load_song, only: [:share, :vote, :play, :show]

  def new
    @song = Song.new

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def create
    @song = Song.new song_params
    @song.user = current_user

    respond_to do |format|
      if @song.save
        format.html { redirect_to share_song_path(@song) }
        format.js { render layout: false }
      else
        format.html { render :new }
        format.js { render :new, layout: false }
      end
    end
  end

  def share
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def vote
    respond_to do |format|
      if current_user.can_vote_for?(@song)
        current_user.vote_for(@song)
        format.js { render layout: false }
      else
        @error = "You have already voted for this song."
        format.js { render layout: false }
      end
    end
  end

  def play
    current_user.play @song

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    def load_song
      @song = Song.find params[:id]
    end

    def song_params
      params.require(:song).permit(:url, :category_id, :for_challenge)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
  def song_meta song
    {
      og: {
        image: song.image.list.url,
        title: song.title,
        site_name: 'Caribbean Dance Music',
        url: song_url(song),
        description: song.description
      }
    }
  end
end

app/views/songs/_form.html.haml
.holder-upload-form
  = simple_form_for(song, remote: true) do |f|
    %h2 Publish your track to CDM

    = f.error_notification

    - if song.errors[:provider_id].present?
      .provider-error
        = song.errors[:provider_id].join
        = surround '(', ')' do
          = link_to 'view', song_path(song.original_song)

    .form-inputs
      %span.hint
        %i *
        Enter the link of your track from Youtube or Soundcloud
      = f.input :url, placeholder: 'http://yourlink', label: false

      %span.hint
        %i *
        Select category genre

      .input.select.required.song_category
        = f.select :category_id, grouped_options_for_select(Category.group_parents, song.category_id), include_blank: 'Select category genre'

    .form-actions.text-right
      = f.input :for_challenge, as: :boolean, label: 'Submit to DJ Competition'
      = f.button :submit, "Submit"

app/views/songs/_iframe_player.haml
- if song.provider == 'youtube'
  %iframe{:allowfullscreen => "", :frameborder => "0", :height => "100%", :src => "https://www.youtube.com/embed/#{song.provider_id}?rel=0&controls=1&showinfo=1&autoplay=1", :width => "100%"}
- elsif song.provider == 'soundcloud'
  %iframe{:frameborder => "no", :height => "100%", :scrolling => "no", :src => "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/#{song.provider_id}&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&visual=true", :width => "100%"}

app/views/songs/new.html.haml
= render partial: 'form', locals: {song: @song}

app/views/songs/share.html.haml
- meta song_meta(@song)

.holder-share
  %h2 Share

  .holder-image
    = image_tag @song.image.list

  .title.m-t-30
    - 3.times do
      = @song.title

  .holder-share-buttons.m-t-30
    = link_to "javascript: void(0)", class: 'share-facebook', onclick: "window.open('#{fb_share_link(song_url(@song))}','sharer','toolbar=0,status=0,width=548,height=325');" do
      %i
      Share On Facebook

    = link_to '#', class: 'share-twitter', onclick: "window.open('#{tw_share_link(song_url(@song))}','sharer','toolbar=0,status=0,width=548,height=325');" do
      %i
      Share on Twitter


  %form
    .form-inputs
      %span.hint Share Links
      %input{name: :url, type: :url, value: song_url(@song)}/


  .text-right.m-t-30
    = link_to 'Done', '#', class: 'btn-done', "data-dismiss" => "modal"

app/views/songs/show.html.haml
- meta song_meta(@song)

.holder-show
  %article.music-item-detailed{id: "song-item-#{@song.id}"}
    .iframe{style: "background-image: url(#{@song.image.list});"}
      -# = image_tag @song.image.list, width: 'auto', height: '400'
      .overlay
        %span.heart
          - if user_signed_in?
            = link_to vote_song_path(@song), remote: true, method: :post do
              %i.icon.icon-heart-white-circle
          - else
            = link_to new_user_session_path, data: {target: "#modal-sign-in", toggle: :modal}, remote: true do
              %i.icon.icon-heart-white-circle
        %span.play
          - if user_signed_in?
            = link_to play_song_path(@song, song_profile: true), class: 'play-song', remote: true do
              %i.icon.icon-play-white-circle
          - else
            = link_to new_user_session_path, class: 'play-song', data: {target: "#modal-sign-in", toggle: :modal}, remote: true do
              %i.icon.icon-play-white-circle

        %span.share
          = link_to share_song_path(@song), remote: true do
            %i.icon.icon-share-white-circle

    %header.header.clearfix
      .title
        %h1= @song.title
      .actions
        %span.plays
          %span.text= @song.plays.size
          plays
        %span.votes
          %i.icon.icon-heart
          %span.text= @song.votes.size
        %span.facebook-shares
          %i.icon.icon-facebook-small
          = facebook_shares song_url(@song)
        %span.twitter-shares
          %i.icon.icon-twitter-small
          = twitter_shares song_url(@song)

    %section.details
      %p.description= @song.description

      %hr

    %footer.footer.clearfix
      .user-info
        .avatar
          = image_tag @song.user.avatar.thumb
        by
        %span.username= link_to @song.user.full_name, user_path(@song.user)
        in CDM
        .time
          = link_to song_path(@song) do
            = time_ago_in_words @song.created_at
            ago
      .actions
        - if user_signed_in?
          = link_to play_song_path(@song, song_profile: true), class: 'cdm-btn play m-r-10 play-song', remote: true do
            %i.icon.icon-play-grey
            Play

          = link_to vote_song_path(@song), class: 'm-r-10', remote: true, method: :post do
            %i.icon.icon-heart-grey
        - else
          = link_to new_user_session_path, class: 'cdm-btn play m-r-10 play-song', data: {target: "#modal-sign-in", toggle: :modal}, remote: true do
            %i.icon.icon-play-grey
            Play

          = link_to new_user_session_path, class: 'm-r-10', data: {target: "#modal-sign-in", toggle: :modal}, remote: true do
            %i.icon.icon-heart-grey

        = link_to share_song_path(@song), remote: true do
          %i.icon.icon-share-grey