config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :omniauth_callbacks,
    registrations: :registrations
  }
  root 'welcome#index'

  get 'explore' => 'welcome#explore', as: :explore
  get 'explore/:category' => 'welcome#explore', as: :explore_category
  get 'challenge' => 'welcome#challenge'
  get 'about' => 'welcome#about'

  scope :upload, controller: :uploads, as: :upload do
    get :new
    post :create
    get 'share/:id', action: :share, as: :share
  end

  resources :songs, only: [:new, :create, :show] do
    member do
      get :share
      post :vote
      get :play
    end
  end

  resources :users, only: [:show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).concat [:full_name, :username, :gender]
    devise_parameter_sanitizer.for(:account_update).concat [
      :full_name, :username, :gender, :website, :facebook_url, :twitter_url,
      :instagram_url, :youtube_url, :soundcloud_url, :avatar, :avatar_cache]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    name = 'page-' + params[:controller].gsub('/', '-') + '-' + params[:action]
    if params[:controller] == "users" and params[:action] == "show"
      name += " #{name}-#{params[:id]}"
    end
    name
  end

  def resource_name
    :user
  end

  def resource_class
    User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def fb_share_link url
    "https://www.facebook.com/sharer/sharer.php?u=#{url}&app_id=#{Figaro.env.facebook_app_id}"
  end

  def tw_share_link url
    "https://twitter.com/intent/tweet?url=#{url}"
  end

  def facebook_shares url
    begin
      url = "http://graph.facebook.com/?id=#{url}"
      return JSON.load(open(url))['shares'] || 0
    rescue
      return nil
    end
  end

  def twitter_shares url
    begin
      url = "https://cdn.api.twitter.com/1/urls/count.json?url=#{url}"
      return JSON.load(open(url))['count'] || 0
    rescue
      return nil
    end
  end

  def categories_menu_extra_class
    return '' if devise_controller?
    (current_page?(controller: :welcome, action: :explore) && params[:category] != 'all' && !params[:category].blank?) ? 'active' : ''
  end

  def challenge_link_extra_class
    return '' if devise_controller?
    (current_page?(controller: :welcome, action: :challenge) ? 'active' : '')
  end

  def url_with_protocol url
    return '#' if url.blank?
    /^http/i.match(url) ? url : "http://#{url}"
  end

end

app/views/application/_categories_menu.haml
.container.container-categories
  .container.holder-categories-filter
    .row
      .holder-for-challenge-filter
        = check_box_tag :for_challenge, true, params[:for_challenge].present?
        = label_tag :for_challenge, "Include only DJ Competition tracks"

        %span.or or view

        = link_to 'All Genres competition tracks ', explore_path(for_challenge: true), class: 'all-genres'

      .col-xs-4.col-sm-2.extra-menu.hidden-sm.hidden-md.hidden-lg
        = render partial: 'application/extra_menu'
      - Category.parents.except(:other).keys.each do |parent|
        .col-xs-4.col-sm-2.categories-menu
          .title
            - if parent == "cdm"
              = parent.humanize.upcase
            - else
              = parent.humanize
          %ul.clearfix.categories
            - Category.send(parent).order('name asc').each do |cat|
              %li
                .holder
                  = link_to cat.name, explore_category_path(cat, params.slice(:top, :sort, :for_challenge).merge({e: 1})), class: (params[:category] == cat.slug ? 'active' : '')
                  - if params[:category] == cat.slug
                    = link_to 'x', explore_path(params.slice(:top, :sort, :for_challenge)), class: 'remove'

      .col-xs-8.col-sm-4.categories-menu
        .title Other
        %ul.clearfix.categories.categories-other
          - Category.other.order('name asc').each do |cat|
            %li
              .holder
                = link_to cat.name, explore_category_path(cat, params.slice(:top, :sort, :for_challenge).merge({e: 1})), class: (params[:category] == cat.slug ? 'active' : '')
                - if params[:category] == cat.slug
                  = link_to 'x', explore_path(params.slice(:top, :sort, :for_challenge)), class: 'remove'

      .col-xs-4.col-sm-2.extra-menu.hidden-xs
        = render partial: 'application/extra_menu'

app/views/application/_extra_menu.haml
%ul
  - unless user_signed_in?
    - if !devise_controller?
      %li.hidden-sm.hidden-md.hidden-lg
        = link_to "Sign Up", new_user_registration_path, data: {target: "#modal-sign-up", toggle: :modal}, remote: true
      %li.hidden-sm.hidden-md.hidden-lg
        = link_to "Login", new_user_session_path, data: {target: "#modal-sign-in", toggle: :modal}, remote: true
    - else
      %li.hidden-sm.hidden-md.hidden-lg
        = link_to "Sign Up", new_user_registration_path
      %li.hidden-sm.hidden-md.hidden-lg
        = link_to "Login", new_user_session_path

  %li
    = link_to about_path, class: 'about' do
      %i.icon.icon-logo-small
      About
  %li
    = link_to '#', class: 'blog' do
      %i.icon.icon-blog
      Blog
  %li
    = link_to 'https://www.facebook.com/cdmgeneration', target: :blank, class: 'facebook' do
      %i.icon.icon-facebook-small
      Facebook
  %li
    = link_to 'https://instagram.com/cdmgeneration/', target: :blank, class: 'instagram' do
      %i.icon.icon-instagram-small
      Instagram
  %li
    = link_to 'https://soundcloud.com/cdmgeneration', target: :blank, class: 'soundcloud' do
      %i.icon.icon-soundcloud-small
      Soundcloud
  %li
    = link_to "DJ Challenge", challenge_path
  - if user_signed_in?
    %li= link_to "Logout", destroy_user_session_path

app/views/application/_modal_sign_in.haml
#modal-sign-in.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "signInUser", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        .clearfix
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &#215;

        = render template: 'devise/sessions/new.html'

app/views/application/_modal_sign_up.haml
#modal-sign-up.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        .clearfix
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &#215;

        = render template: 'devise/registrations/new.html'

app/views/application/_modal_upload.haml
#modal-upload.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "upload", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        .clearfix
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &#215;

        .content

app/views/application/_player.haml
.iframe
  - if song.provider == 'youtube'
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/#{song.provider_id}?rel=0&controls=1&showinfo=1&autoplay=1", :width => "560"}
  - elsif song.provider == 'soundcloud'
    %iframe{:frameborder => "no", :height => "315", :scrolling => "no", :src => "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/#{song.provider_id}&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&visual=true", :width => "560"}

.song-info{id: "song-player-#{song.id}"}
  %a.close-player{data: {song_id: "#{song.id}"}} x
  = render partial: 'songs/details/details', locals: {song: song}
  = render partial: 'songs/details/footer', locals: {song: song}