config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :omniauth_callbacks,
    registrations: :registrations
  }
  root 'welcome#index'

  get 'explore' => 'welcome#explore', as: :explore
  get 'explore/:category' => 'welcome#explore', as: :explore_category
  get 'challenge' => 'welcome#challenge'
  get 'about' => 'welcome#about'

  scope :upload, controller: :uploads, as: :upload do
    get :new
    post :create
    get 'share/:id', action: :share, as: :share
  end

  resources :songs, only: [:new, :create, :show] do
    member do
      get :share
      post :vote
      get :play
    end
  end

  resources :users, only: [:show]
end

app/views/layouts/application.haml
- meta fb: {app_id: Figaro.env.facebook_app_id}
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    = metamagic
    %title CDM Website
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false
    = csrf_meta_tags
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body{class: body_class}
    .wrapper
      %nav.navbar.navbar-default.navbar-fixed-top#header
        .container.main-container
          .navbar-header
            = link_to root_path, class: 'navbar-brand' do
              %i.logo

            = link_to '#', class: "categories-menu #{categories_menu_extra_class}" do
              .holder-borders
                %span.border
                %span.border
                %span.border
              Explore
              %span.arrow-down

            = link_to 'DJ Challenge', challenge_path, class: "challenge #{challenge_link_extra_class}"

          .holder-title.text-center
            .title
              - if content_for :header_title
                = yield :header_title
              - else
                %i.icon.icon-arrow-trend
                Most Popular

          #navbar.collapse.navbar-collapse
            %ul.nav.navbar-nav
              - if user_signed_in?
                %li.upload= link_to "Upload", new_song_path, remote: true
              - elsif !user_signed_in? and !devise_controller?
                %li= link_to "Sign Up", new_user_registration_path, data: {target: "#modal-sign-up", toggle: :modal}, remote: true
                %li= link_to "Login", new_user_session_path, data: {target: "#modal-sign-in", toggle: :modal}, remote: true
              - else
                %li= link_to "Sign Up", new_user_registration_path
                %li= link_to "Login", new_user_session_path
            - if user_signed_in?
              .user-info
                %span.avatar= image_tag current_user.avatar.thumb
                = link_to current_user.first_name, user_path(current_user)
                - if false
                  %ul
                    %li= link_to "Logout", destroy_user_session_path

      -# %p.notice= notice
      -# %p.alert= alert
      = yield :slider
      = yield :challenge
      = yield :about

      = render partial: 'application/categories_menu'

      - unless content_for?(:slider) or content_for?(:challenge) or content_for?(:about)
        #player
        #content
          .container
            = yield

      .push
    %footer#footer
      .container
        .col-xs-8
          .links
            = link_to root_path, class: 'logo-link'  do
              %i.logo-slim
            = link_to 'About', about_path
            = link_to 'Blog', '#'
            %span.hidden-xs @2015 CDM
        .col-xs-4
          .socials
            = link_to 'https://www.facebook.com/cdmgeneration', target: :blank do
              %i.icon.icon-facebook-white-tiny
            = link_to 'https://soundcloud.com/cdmgeneration', target: :blank do
              %i.icon.icon-soundcloud-white-tiny
            = link_to 'https://instagram.com/cdmgeneration/', target: :blank do
              %i.icon.icon-instagram-white-tiny

    - unless user_signed_in?
      = render partial: 'application/modal_sign_up'
      = render partial: 'application/modal_sign_in'

    = render partial: 'application/modal_upload'

    #fb-root

    = javascript_include_tag 'application', 'data-turbolinks-track' => false